version: '3.7'
services:
  #====================================================================================================================#
  #================================================== tomcat-jre install ==============================================#
  #====================================================================================================================#
  # 1.默认: 放置ROOT目录 8080端口  访问地址：http://112.74.185.172:8080/    ->  修改IP即可
  tomcat:
    hostname: tomcat
    # only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
    container_name: tomcat
    # 2.解决容器的依赖、启动先后的问题
    depends_on:
      - mysql
      - redis_master
      - redis_slave
      - rabbitmq
    links:
      - mysql
      - redis_master
      - redis_slave
      - rabbitmq
    # 3.选择自己镜像构建的方式 -> image: 远程仓库拉取 or build:上下文构建(可对项目代码进行)
    #    image: tomcat:8.5.35-jre8
    build: ./tomcat
    # 4.可通过./tomcat/conf/server.xml设置服务端口
    ports:
      - 8080:8080
    # 5.定义IP网络
    networks:
      app_net:
        ipv4_address: 172.20.1.2
    #    - 80:80
    #    - 443:443
    # 6.挂载目录
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/logs:/usr/local/tomcat/logs
      - ./tomcat/conf:/usr/local/tomcat/conf
    # 7.设置环境变量: 时区与编码
    #   你可以使用数组或字典两种格式
    #   只给定名称的变量会自动获取运行 Compose 主机上对应变量的值，可以用来防止泄露不必要的数据
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    # 8.生产环境配置：指定容器退出后的重启策略为始终重启, 对保持服务始终运行十分有效
    restart: always
  #    restart: unless-stopped
  #====================================================================================================================#
  #================================================== mysql install ===================================================#
  #====================================================================================================================#
  mysql:
    hostname: mysql
    container_name: mysql-8.0.16
    # 1. 选择自己镜像构建的方式 -> image: 远程仓库拉取 or build:上下文构建
    #    image: mysql:8.0.16
    build: ./mysql
    ports:
      - 3306:3306
    # 2. 定义IP网络
    networks:
      app_net:
         ipv4_address: 172.20.1.3
    environment:
      # 3. 设置数据库密码等
      MYSQL_ROOT_PASSWORD: root7777
      #      MYSQL_DATABASE: xxx
      #      MYSQL_USER: xxx
      #      MYSQL_PASSWORD: xxx123456
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      # 4. 指定自定义的mysql配置文件./mysql/conf/custom.cnf启动数据库
      - ./mysql/conf:/etc/mysql/conf.d
      # 5. 挂载数据存储目录,持久化数据库.
      - ./mysql/data:/var/lib/mysql
      # 6. 挂载数据库定时自动备份目录,见 ./mysql : Dockerfile - > backup.sh ★★★ 填写：备份数据库名/用户名/密码 ★★★
      #- ./mysql/backup:/backup

    # 7. 挂载日志：通用日志,错误日志,慢日志,二进制日志等 -> 具体可见./mysql/conf/custom.cnf

    # 8. 数据恢复
    # 1>进入容器
    ## docker exec -it e7 bash
    # 2>binlog 日志内容解析
    ## mysqlbinlog --no-defaults /var/lib/mysql/mysql-bin.000004
    # 3>找到恢复到时间点
    ## mysqlbinlog --no-defaults --stop-datetime='2018-12-12 15:33:29' /var/lib/mysql/mysql-bin.000004 |mysql -uroot -p

    # 9. TODO 主从复制

    # 9. TODO 读写分离

    # 生产环境配置：指定容器退出后的重启策略为始终重启, 对保持服务始终运行十分有效
    restart: always
  #    restart: unless-stopped
  #====================================================================================================================#
  #================================================== redis install ===================================================#
  #====================================================================================================================#
  redis_master:
    hostname: redis-master
    container_name: redis-master-5.0.4
    # 1.选择自己镜像构建的方式 -> image: 远程仓库拉取 or build:上下文构建
    #    image: redis:5.0.4
    build: ./redis-master
    ports:
      - 6379:6379
    # 2.定义IP网络
    networks:
      app_net:
        ipv4_address: 172.20.1.4
    volumes:
      - ./redis-master/data:/data
      # 3.设置redis配置文件：./redis/conf/redis.conf 默认设置内容如下：
      ### requirepass root7777
      ### bind: 0.0.0.0
      ### loglevel notice
      ### logfile "redis.log"
      - ./redis-master/conf/redis.conf:/usr/local/etc/redis/redis.conf
    # 生成容器后要执行的命令
    command: redis-server /usr/local/etc/redis/redis.conf
    # 4.设置环境变量: 时区与编码
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    # 5.生产环境配置：指定容器退出后的重启策略为始终重启, 对保持服务始终运行十分有效
    restart: always

  redis_slave:
    hostname: redis-slave
    container_name: redis-slave-5.0.4
    # 1.选择自己镜像构建的方式 -> image: 远程仓库拉取 or build:上下文构建
    #image: redis:5.0.4
    build: ./redis-slave
    ports:
      - 6380:6380
    # 2.定义IP网络
    networks:
      app_net:
        ipv4_address: 172.20.1.5
    volumes:
      - ./redis-slave/data:/data
      # 3.设置redis配置文件：./redis/conf/redis.conf 默认设置内容如下：
      ### requirepass root7777
      ### bind: 0.0.0.0
      ### loglevel notice
      ### logfile "redis.log"
      ### port 6380
      ### masterauth root7777
      ### slaveof redis_master 6379
      - ./redis-slave/conf/redis.conf:/usr/local/etc/redis/redis.conf
    # 生成容器后要执行的命令
    command: redis-server /usr/local/etc/redis/redis.conf
    # 4.设置环境变量: 时区与编码
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    # 5.生产环境配置：指定容器退出后的重启策略为始终重启, 对保持服务始终运行十分有效
    restart: always
  #====================================================================================================================#
  #================================================== rabbitmq install ================================================#
  #====================================================================================================================#
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq-3.8.0
    # 选择自己镜像构建的方式 -> image: 远程仓库拉取 or build:上下文构建
    #    image: rabbitmq
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    # 定义IP网络
    networks:
      app_net:
        ipv4_address: 172.20.1.6
    volumes:
      - ./rabbitmq/data:/data/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always

# 定义网络
networks:
  app_net:
    ipam:
      config:
        - subnet: 172.20.1.0/24